import { readFile, writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { build } from 'esbuild';

export const repositoryRoot = fileURLToPath(new URL('../', import.meta.url));
export const distributionName = 'dist/My List for Netflix.user.js';

function metadataHeader(metadata, version) {
    if (Object.hasOwn(metadata, 'version')) throw new Error('Version belongs only in package.json');
    const lines = ['// ==UserScript=='];
    function add(key, value) {
        if (!/^[a-z][a-z-]*$/i.test(key)) throw new Error('Invalid userscript metadata key: ' + key);
        for (const entry of Array.isArray(value) ? value : [value]) {
            if (entry === false) continue;
            if (entry !== true && (typeof entry !== 'string' || /[\r\n]/.test(entry))) {
                throw new Error('Invalid userscript metadata value: ' + key);
            }
            lines.push(entry === true ? '// @' + key : '// @' + key.padEnd(13) + entry);
        }
    }
    add('name', metadata.name);
    add('version', version);
    for (const [key, value] of Object.entries(metadata)) if (key !== 'name') add(key, value);
    lines.push('// ==/UserScript==', '', '// Generated by npm run build. Edit src/ and metadata, then rebuild.');
    return lines.join('\n');
}

// Pure generation with respect to repository files: build, checks and tests share this boundary.
export async function generateUserscript({ root = repositoryRoot } = {}) {
    const packageInfo = JSON.parse(await readFile(path.join(root, 'package.json'), 'utf8'));
    const metadata = JSON.parse(await readFile(path.join(root, 'userscript.meta.json'), 'utf8'));
    if (!/^\d+\.\d+\.\d+$/.test(packageInfo.version)) throw new Error('Invalid userscript release version');
    if (process.versions.node !== packageInfo.engines.node) {
        throw new Error(`Build requires Node ${packageInfo.engines.node}; running ${process.versions.node}`);
    }
    const result = await build({
        absWorkingDir: root,
        entryPoints: ['src/main.js'],
        outfile: distributionName,
        bundle: true,
        platform: 'browser',
        format: 'iife',
        target: 'es2022',
        charset: 'ascii',
        minify: false,
        treeShaking: false,
        legalComments: 'inline',
        sourcemap: false,
        metafile: true,
        write: false,
        logLevel: 'silent',
        define: { __SCRIPT_VERSION__: JSON.stringify(packageInfo.version) },
        banner: { js: metadataHeader(metadata, packageInfo.version) }
    });
    if (result.outputFiles.length !== 1) throw new Error('Build must produce exactly one userscript');
    return { code: result.outputFiles[0].text, metafile: result.metafile, metadata, version: packageInfo.version };
}

if (process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href) {
    const result = await generateUserscript();
    await mkdir(path.dirname(path.join(repositoryRoot, distributionName)), { recursive: true });
    await writeFile(path.join(repositoryRoot, distributionName), result.code, 'utf8');
    console.log(`Built ${distributionName} v${result.version}`);
}
